### PR TITLE
Add favicon to meta data

### PR DESCRIPTION
**Pull request by LarchLiu**
In some cases, I might want to retrieve the `favicon` of a website, so I add it.

### CODE REVIEW

**Comment by LarchLiu** [comment]
I checked this issue #120. As you may know, in China, we do not have access to Google. Therefore, I would like to add this feature if it is possible.

**Comment by ndaidong** [comment]
@LarchLiu thank you, let me see the pr.

**Comment by ndaidong** [comment]
@LarchLiu I've released v7.2.17 with your pr. Thank you for your contributions.

**Comment by LarchLiu** [comment]
@ndaidong Thanks a lot. It is very helpful to me.

**Pull request merged**
